### PR TITLE
Coping with compression change for linux download

### LINKED ISSUE #621: linux(64) (latest-nightly) URL downloads a tar.xz file while setup-firefox expects a bzip2 file
```
Run browser-actions/setup-firefox@v1
Setup firefox latest-nightly (en-US)
Attempting to download firefox latest-nightly...
Acquiring latest-nightly from https://download.mozilla.org/?product=firefox-nightly-latest&os=linux64&lang=en-US
Extracting Firefox...
/usr/bin/tar xj --strip-components=1 --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/843d8cef-b61b-4e46-8081-b[7](https://github.com/ansys-internal/adage-geoview/actions/runs/12065180969/job/33659328230?pr=437#step:8:8)35546e9d88 -f /home/runner/work/_temp/e[8](https://github.com/ansys-internal/adage-geoview/actions/runs/12065180969/job/33659328230?pr=437#step:8:9)d18d26-82cd-4ed6-b6e3-d8545cd847b8
bzip2: (stdin) is not a bzip2 file.
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
Error: The process '/usr/bin/tar' failed with exit code 2
```

https://download.mozilla.org/?product=firefox-nightly-latest&os=linux64&lang=en-US downloads a tar.xz file.

### PR DESCRIPTION
**Pull request by david-dick**
This change will allow the package to cope with recent firefox packages for linux.  Fixes #621

### CODE REVIEW

File: src/DownloadURL.ts [hunk 1]
```diff
@@ -63,11 +63,18 @@ export class ArchiveDownloadURL implements DownloadURL {
 
   private filename(): string {
     const { os } = this.platform;
+    console.log(
+      `This is the version number:${Number.parseInt(this.versionPart(), 10)}`,
+    );
```
Comment (ueokande) [inline src/DownloadURL.ts:69]: Do not use `console.log` here. Please use `core.info()` or `core.debug()` instead.

File: src/Installer.ts [hunk 2]
```diff
@@ -57,8 +57,20 @@ export class LinuxInstaller implements Installer {
 
     const archivePath = await tc.downloadTool(url);
     core.info("Extracting Firefox...");
+    const handle = await fs.promises.open(archivePath, "r");
+    const firstBytes = new Int8Array(3);
+    if (handle !== null) {
+      await handle.read(firstBytes, 0, 3, null);
+      core.info(
+        `Extracted ${firstBytes[0]}, ${firstBytes[1]} and ${firstBytes[2]}`,
+      );
```
Comment (ueokande) [inline src/Installer.ts:66]: This message would be inconvenient for users. I want to propose to replace with `core.debug()`

**Review by ueokande — CHANGES_REQUESTED** [review]
Thanks for your proposal. Please please take a look at my comments.

File: src/Installer.ts (hunk 2 above)
Comment (david-dick) [reply src/Installer.ts:66]: Does that look okay?

File: src/DownloadURL.ts (hunk 1 above)
Comment (david-dick) [reply src/DownloadURL.ts:69]: done

**Comment by dblock** [comment]
This broke my setup, see https://github.com/browser-actions/setup-firefox/issues/625.
